config/routes.rb
# Rails.application.routes.draw do
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#   # cocktails routes
#   resources :cocktails, only: [:index, :show, :new, :create, :destroy] do
#     resources :doses
#   end
#   resources :doses, only: [:destroy, :new, :create, :show]

# end

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:create]
  end
  resources :doses, only: [:destroy]

  root to: "cocktails#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :ingredient, :scope => :cocktail
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktail_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def new
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @dose = Dose.new
  # end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/index.html.erb
<div class="container">
    <h1>Mixter Cocktail</h1>
      <p>This challenge is tough!!</p>
          <%= link_to "Add a cocktail", new_cocktail_path, class: "btn btn-primary btn-lg" %>

    <div class="row">
        <% @cocktails.each do |cocktail| %>
      <div class="col-4">
          <h2><%= link_to "#{cocktail.name}", cocktail_path(cocktail) %></h2>
          <%= cl_image_tag cocktail.photo.key, height: 251, width: 300, crop: :fill %>
            <%= link_to "", cocktail_path(cocktail), class: 'card-link' %>
      </div>
        <% end %>
    </div>
</div>

app/views/cocktails/new.html.erb
<!--  link_to "", cocktail_path(cocktail), class: 'card-link'

link_to 'Back to all cocktails', cocktails_path  -->

<!-- link_to 'Lets try this again...', new_cocktail_dose_path(:cocktail_id)

link_to 'Finish List', doses_url(:id)
 -->

<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h1>Create a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<!-- this is where the partial form is rendered -->

<div class="container">

  <h1><%= @cocktail.name %></h1>
  <%= link_to "Back to all cocktails", root_path %>
  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
    <p></p>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td><%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %><i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-6">
      <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
    </div>
  </div>

</div>

app/views/doses/_new.html.erb
<!--   f.submit "Complete Cocktail", class: "btn btn-primary"
end
link_to 'Back to all cocktails', cocktails_path
link_to 'Delete dose', dose_path(:id), method: :delete -->


<h3>Add a new dose</h3>
<%= simple_form_for [cocktail, dose] do |f| %>
  <%= f.association :ingredient%>
  <%= f.input :description %>
  <%#= f.input :photo, as: :file %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <body>
    <%= yield %>
      <%= javascript_include_tag "application" %>
      <%= javascript_pack_tag "application" %>
  </body>
</html>